title: Sten Raak # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Highly motivated and looking for challenges in the data analytics and science department. I am currently a teaching assistant while also studying 
  at the University of Tartu, teaching other professions about probabilities and statistics. At the same time I am
  also working as a Business Data Analyst at Bondora to provide valuable insights and maintaining categorization models.
  <a href="https://www.linkedin.com/in/sten-raak-a8a6b115b/"> View My LinkedIn Profile </a> 
  <br>
  
  
theme: jekyll-theme-minimal
