title: Sten Raak # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Highly motivated and looking for challenges in the data analytics and science department. Studying mathematical statistics in the 3rd year. 
  I am currently a teaching assistant at the University of Tartu, teaching other professions about probabilities and statistics. At the same time I am
  also working as a Business Data Analyst at Bondora to provide valuable insights and maintain a categorization model in different countries.
  <br><br>
  <a href="https://www.linkedin.com/in/sten-raak-a8a6b115b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
